language: node_js
install: 
  - npm install
jobs:
  include:
    - stage: test
      node_js:
        - 10
      name: "Unit Testing"
      script: jest ./test/unit.test.js
    - script: jest ./test/integration.test.js
      name: "Integration Testing"
    - stage: deploy
      name: "Deploy to Heroku"
      if: branch = master
      deploy:
        skip_cleanup: true
        provider: heroku
        api_key:
          secure: 99e971fd-ded9-4202-a90a-74217c1b5dbb
        app: ewutest
        on:
          repo: ewujs/ci-test
          branch: master