language: node_js
node_js:
  - node
before_install:
  - stty cols 80
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
cache: npm
script: skip
jobs:
  include:
    - stage: test
      if: type = pull_request AND branch = development
      name: "Unit Testing"
      script: jest ./test/unit.test.js
    - stage: test
      script: jest ./test/integration.test.js
      if: type = pull_request AND branch = development
      name: "Integration Testing"
    - stage: deploy to staging
      if: type = push AND branch = development
      name: "Deploy to Heroku"
      script: skip
      deploy:
        skip_cleanup: true
        provider: heroku
        api_key:
          secure: 99e971fd-ded9-4202-a90a-74217c1b5dbb
        app: ewutest
        on: development
    - stage: test staging
      if: type = pull_request AND branch = development
      name: "Staging Testing"
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &
      script: testcafe chrome index-test.js