language: node_js
node_js:
  - 10
  - 9
  - 8
  - 7
install:
    - npm install
script:
    - npm run test
deploy:
  provider: heroku
  api_key:
    secure: 99e971fd-ded9-4202-a90a-74217c1b5dbb
  app: ewutest
  on: ewujs/ci-test