language: node_js
node_js:
  - node
before_install:
  - stty cols 80
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
cache: npm
script: skip
jobs:
  include:
    - script: jest ./test/unit.test.js
      name: "Unit Testing"
    - script: jest ./test/integration.test.js
      name: "Integration Testing"
    - stage: deploy
      name: "Deploy to Heroku"
      if: branch = development
      deploy:
        script: skip
        skip_cleanup: true
        provider: heroku
        api_key:
          secure: 99e971fd-ded9-4202-a90a-74217c1b5dbb
        app: ewutest
        on:
          repo: ewujs/ci-test
          branch: development
      after_deploy:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &
        - testcafe chrome index-test.js